import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

const pageSource = readFileSync(new URL('./OrderLabelsPage.jsx', import.meta.url), 'utf8')
const previewSource = readFileSync(new URL('./labels/OrderLabelsPreview.jsx', import.meta.url), 'utf8')
const resultsSource = readFileSync(new URL('./labels/OrderLabelsResults.jsx', import.meta.url), 'utf8')
const cssSource = readFileSync(new URL('./labels/order-labels.css', import.meta.url), 'utf8')
const configSource = readFileSync(new URL('./labels/labelPrintConfig.js', import.meta.url), 'utf8')

describe('order labels print flow', () => {
  it('prints directly from the selected labels without entering preview mode', () => {
    expect(pageSource).toContain('window.print()')
    expect(pageSource).toContain('onClick={printSelectedLabels}')
    expect(pageSource).toContain('showControls={false}')
    expect(pageSource).toContain('printDiagnosticsEnabled')
    expect(pageSource).toContain('Diagnóstico')
    expect(pageSource).toContain('Imprimir prueba de calibración')
    expect(pageSource).toContain("document.body.classList.add('labels-print-mode')")
    expect(pageSource).toContain("document.body.classList.remove('labels-print-mode')")
    expect(pageSource).not.toContain('labels.markPrinted')
    expect(pageSource).toContain('Seleccionar todos visibles')
    expect(pageSource).toContain('1 pedido = 1 etiqueta')
    expect(pageSource).not.toContain('labels.enterPreview')
    expect(pageSource).not.toContain('labels.previewMode')
  })

  it('separates printed and pending labels and keeps printed labels reprintable', () => {
    expect(resultsSource).toContain('Falta imprimir')
    expect(resultsSource).toContain('Ya impreso')
    expect(resultsSource).toContain('Reimprimir')
    expect(resultsSource).toContain('onPrintStateChange')
  })

  it('prints each selected label as a separate page or ticket', () => {
    const physicalWidthMm = 100
    const physicalHeightMm = 50
    const safePaddingMm = 2
    const safeWidthMm = physicalWidthMm - (safePaddingMm * 2)
    const safeHeightMm = physicalHeightMm - (safePaddingMm * 2)

    expect(safeWidthMm).toBeLessThanOrEqual(physicalWidthMm)
    expect(safeHeightMm).toBeLessThanOrEqual(physicalHeightMm)
    expect(safePaddingMm).toBeGreaterThanOrEqual(0)
    expect(physicalWidthMm - safeWidthMm - safePaddingMm).toBe(safePaddingMm)
    expect(physicalHeightMm - safeHeightMm - safePaddingMm).toBe(safePaddingMm)

    expect(cssSource).toContain('.print-label {')
    expect(cssSource).toContain('width: var(--thermal-label-width, 100mm) !important')
    expect(cssSource).toContain('height: var(--thermal-label-height, 50mm) !important')
    expect(cssSource).toContain('padding: 0 !important')
    expect(cssSource).toContain('.print-label .label-content')
    expect(cssSource).toContain('padding: var(--thermal-label-safe-padding, 2mm) !important')
    expect(cssSource).toContain('box-sizing: border-box !important')
    expect(cssSource).toContain('transform: translate(var(--label-offset-x, 0mm), var(--label-offset-y, 0mm)) !important')
    expect(cssSource).toContain('-webkit-transform: translate(var(--label-offset-x, 0mm), var(--label-offset-y, 0mm)) !important')
    expect(cssSource).toContain('break-after: page !important')
    expect(cssSource).toContain('page-break-after: always !important')
    expect(cssSource).toContain('.print-label:last-child')
    expect(cssSource).toContain('break-after: auto !important')
    expect(cssSource).not.toContain('@page')
    expect(previewSource).toContain('{`@page { size: ${printPageSize}; margin: 0; }`}')
    expect(cssSource).toContain('.labels-print-root-screen-hidden')
    expect(cssSource).toContain('body.labels-print-mode > :not(.labels-preview-root)')
    expect(cssSource).not.toContain('body:has(')
    expect(previewSource).toContain('createPortal(preview, document.body)')
    expect(previewSource).toContain('--thermal-label-safe-padding')
    expect(previewSource).toContain('--label-offset-x')
    expect(previewSource).toContain('--label-offset-y')
    expect(previewSource).toContain('diagnosticsEnabled')
    expect(previewSource).toContain('getBoundingClientRect()')
    expect(previewSource).toContain('Clasificacion')
    expect(previewSource).toContain('TAMANO/ESCALA')
    expect(previewSource).toContain('DOM OK')
    expect(previewSource).toContain("window.addEventListener('beforeprint', measureDiagnostics)")
    expect(previewSource).toContain('labels-print-container')
    expect(previewSource).toContain('className="print-label"')
    expect(previewSource).toContain('className="label-content"')
    expect(previewSource).toContain('label-calibration-test')
    expect(cssSource).toContain('.labels-diagnostics-enabled .print-label')
    expect(cssSource).toContain('.labels-diagnostics-enabled .label-content')
    expect(cssSource).toContain('.label-diagnostics-panel')
    expect(configSource).toContain('labelPrintOffsetX')
    expect(configSource).toContain('labelPrintOffsetY')
    expect(configSource).toContain('min: -5')
    expect(configSource).toContain('max: 5')
    expect(configSource).toContain('step: 0.25')
  })
})
